<?php

namespace AppBundle\Repository;

/**
 * ClientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClientRepository extends \Doctrine\ORM\EntityRepository
{
    public function findOneByIdJoinedToChildren($clientId)
    {
        $query = $this->getEntityManager()
            ->createQueryBuilder()
            ->select('c', 'p', 'e')
            ->from('AppBundle:Client', 'c')
            ->leftJoin('c.phonenumbers', 'p', 'WITH', 'p.deleted = 0')
            ->leftJoin('c.emails', 'e', 'WITH', 'e.deleted = 0')
            ->where('c.id = :id')
            ->setParameter('id', $clientId)
            ->getQuery();

        try {
            return $query->getSingleResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }
}
