<?php

namespace AppBundle\Repository;

/**
 * PhonenumberRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PhonenumberRepository extends \Doctrine\ORM\EntityRepository
{
}
