<?php

namespace AppBundle\Repository;

/**
 * TypeLabelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeLabelRepository extends \Doctrine\ORM\EntityRepository
{
}
